name: Test 

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup RT-Thread
      uses: maikebing/rt-thread_linux_env@main 
      with: 
           TARGET: 'mdk5'
           CPPCHECK: '--enable=all --std=c99 applications/'
 
